# Generated by Django 4.1.5 on 2023-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('numero', models.CharField(blank=True, max_length=100, verbose_name='Numéro')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('Description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
            ],
        ),
    ]
