# Generated by Django 4.1.5 on 2023-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_description_customer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qr_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
