# Generated by Django 4.1.5 on 2023-02-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customer_qr_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='signature_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='BDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
            ],
        ),
    ]
