# Generated by Django 4.1.5 on 2023-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customer_signature_path_bdl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdl',
            name='date_livraison',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
