# Generated by Django 4.1.5 on 2023-02-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_bdl_date_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdl',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
