# Generated by Django 4.1.5 on 2023-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rename_is_signed_bdl_is_signed_kd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='signature_client_commande_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
