# Generated by Django 4.1.5 on 2023-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_customer_date_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_signed_commande',
            field=models.BooleanField(default=False),
        ),
    ]
