# Generated by Django 4.1.5 on 2023-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_customer_is_signed_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='to_deliver',
            field=models.BooleanField(default=False),
        ),
    ]
