# Generated by Django 4.1.5 on 2023-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_customer_to_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
    ]
