# Generated by Django 4.1.5 on 2023-03-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_customer_nom_alter_customer_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
