# Generated by Django 4.1.5 on 2023-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom'),
        ),
    ]
