# Generated by Django 4.1.5 on 2023-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_customer_nom_alter_customer_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom')),
                ('numero', models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
    ]
