# Generated by Django 4.1.5 on 2023-03-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email2',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email2',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
        ),
    ]
