# Generated by Django 4.1.5 on 2023-04-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_customer_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email2',
            field=models.EmailField(default='', max_length=254, null=True, verbose_name='email address'),
        ),
    ]
