# Generated by Django 4.1.5 on 2023-04-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_customer_email2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email2',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email2',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
        ),
    ]
